AdrileBoutique/AdrileBoutique/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
from appTiendaInventario import views

# router para las rutas de la Api
router = DefaultRouter()
router.register(r'usuarios', views.UsuarioViewSet)
router.register(r'categorias', views.CategoriaViewSet)
router.register(r'categoriasCliente', views.CategoriaViewSetCliente)
router.register(r'proveedores', views.ProveedorViewSet)
router.register(r'productos', views.ProductoViewSet)
router.register(r'productosCliente', views.ProductoViewSetCliente)
router.register(r"productosPagination", views.ProductoPaginationViewSet)
router.register(r"productosPaginacionLimit", views.ProductoPaginationLimitViewSet)
router.register(r'clientes', views.ClienteViewSet)
router.register(r'compras', views.CompraViewSet)
router.register(r'detalles_compra', views.DetalleCompraViewSet)
router.register(r'ventas', views.VentaViewSet)
router.register(r'detalles_venta', views.DetalleVentaViewSet)
router.register(r'detalles_venta_por_venta', views.DetalleVentaPorVentaViewSet , basename='detalles_venta_por_venta')
router.register(r'detalles_compra_por_compra', views.DetalleCompraPorCompraViewSet , basename='detalles_compra_por_compra')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name='inicio'),
    path('', views.index, name='login'),
    path('inicio/', views.inicioTienda, name='inicio_tienda'),
    # rutas de la Api
    path("api/", include(router.urls)),
    # URL para iniciar sesión y para cerrar sesión web y api 
    path('login/', views.login_view, name='login'),
    path("logout/", views.custom_logout, name="logout"),
    path('api/login/', views.login_api_view, name='api_login'),
     path('api/logout/', views.logout_api_view, name='api_logout'),
    
    # gestion de Perfil
    path("perfil/<int:usuario_id>/", views.perfil_usuario, name="perfil"),
    # path("/modificarUsuario/<int:usuario_id>/", views.modificarDatosUserPerfil(), name="modificar_perfil"),
    
    # URL de gestion inventario
    path('dashboard/', views.dashboard, name='dashboard'),
    path("frmCategorias/", views.categorias, name="categorias"),
    path("frmProductos/", views.productos, name="productos"),
    path("frmEntradas/", views.entradas, name="entradas"),
    path("frmSalidas/", views.salidas, name="salidas"),
    path('lista_compras/', views.lista_compras, name='lista_compras'),
    path('lista_ventas/', views.lista_ventas, name='lista_ventas'),
    path('proveedores/', views.proveedores, name='proveedores'),
    path('clientes/', views.clientes, name='clientes'),
    path('actualizarPerfil/<int:usuario_id>/', views.modificarDatosUserPerfil),
    
    #----------- tienda ---------------------------------------
    path('inicio/', views.inicioTienda, name='inicio_tienda'),
    path('tienda/', views.inicio_Tienda, name='tienda'),
    path('acerca/', views.acercaDe, name='acerca'),
    path('contactanos/', views.contactanos, name='contactanos'),
    path('contact/',views.contact),
    path('enviarCorreo', views.enviarCorreo),
    path("detalle_producto/", views.detalleProduto, name="detalle_producto"),
    
    # funciones extras
    path('productos_por_proveedor/<int:proveedor_id>/', views.productos_por_proveedor, name='productos_por_proveedor'),
    path('productos/categoria/<int:categoria_id>/', views.ProductosPorCategoriaViewSet.as_view({'get': 'list'}), name='productos_por_categoria'),
    path('informes_combinados/', views.informes_combinados, name='informes_combinados'),
    path('recuperar-contrasena/', views.CustomPasswordResetView.as_view(), name='custom_password_reset'),
    # rutas para restablecer contraseña (Admin)
    path("validarCorreo/", views.restPasswordRequest, name="validarCorreo"),
    path("nuevaContra/", views.restPassword, name="nuevaContra"),
    path("mensajeCorreo/", views.mensajeCorreo, name="mensajeCorreo"),
    path("resetLink/", views.PasswordResetRequestView.as_view(), name="resetLink"),
    path("resetPassword/", views.PasswordResetView.as_view(), name="resetPassword"),
    
    # formularios pruebas sin diseño
    path('lista_stock/', views.lista_stock, name='lista_stock'),
    path('informe_ventas/', views.informe_ventas, name='informe_ventas'),
    
    path('agregar_producto/', views.agregar_producto, name='agregar_producto'),
    path('editar_producto/<int:producto_id>/', views.editar_producto, name='editar_producto'),
    path('cambiar_estado/<int:producto_id>/', views.cambiar_estado, name='cambiar_estado'),
    path('lista_productos/', views.lista_productos, name='lista_productos'),
    
    
    path('agregar_categoria/', views.agregar_categoria, name='agregar_categoria'),
    path('editar_categoria/<int:categoria_id>/', views.editar_categoria, name='editar_categoria'),
    path('lista_categorias/', views.lista_categorias, name='lista_categorias'),
    
    
    path('agregar_proveedor/', views.agregar_proveedor, name='agregar_proveedor'),
    path('editar_proveedor/<int:proveedor_id>/', views.editar_proveedor, name='editar_proveedor'),
    path('lista_proveedores/', views.lista_proveedores, name='lista_proveedores'),
    
     
    path('agregar_cliente/', views.agregar_cliente, name='agregar_cliente'),
    path('editar_cliente/<int:cliente_id>/', views.editar_cliente, name='editar_cliente'),
    path('lista_clientes/', views.lista_clientes, name='lista_clientes'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AdrileBoutique/appTiendaInventario/models.py
from django.db import models
from django.contrib.auth.models import User,Group
from django.db.models.signals import post_migrate
from django.dispatch import receiver

# Create your models here.
class GroupCreator(models.Model):
    class Meta:
        verbose_name_plural = 'Group Creator'

@receiver(post_migrate)
def create_groups(sender, **kwargs):
    # Define los nombres de los grupos que deseas crear
    group_names = ['administrador', 'empleado']

    # Itera sobre los nombres de los grupos y créalos si no existen
    for group_name in group_names:
        group, created = Group.objects.get_or_create(name=group_name)
        if created:
            print(f'Se ha creado el grupo: {group_name}')
            
#================================= Usuarios ==============================================
class Usuario(User):
    direccion = models.CharField(max_length=45)
    telefono = models.CharField(max_length=45)
    fotoPerfil = models.ImageField(upload_to="perfiles/", blank=True, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.username

# ================================= Categorias ==============================================
class Categoria(models.Model):
    nombre = models.CharField(max_length=45, unique=True)
    imagen = models.ImageField(upload_to="categorias/", blank=True, null=True)
    categoria_padre = models.ForeignKey('self', null=True, blank=True, on_delete=models.PROTECT)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.nombre

# ================================= Proveedores ========================
class Proveedor(models.Model):
    nombre_empresa = models.CharField(max_length=100)
    nombre_contacto = models.CharField(max_length=100)
    direccion = models.TextField()
    telefono = models.CharField(max_length=20)
    correo_electronico = models.EmailField()
    notas = models.TextField(blank=True, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.nombre_empresa
    
# ============================== Productos ===========================
DISPONIBLE = True
AGOTADO = False
ESTADO_CHOICES = [
        (DISPONIBLE, 'Disponible'),
        (AGOTADO, 'Agotado'),
    ]
class Producto(models.Model):
    codigo = models.IntegerField(unique=True,null=True)
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    imagen = models.ImageField(upload_to="productos/", blank=True, null=True)
    estado = models.BooleanField(choices=ESTADO_CHOICES, default=DISPONIBLE)
    talla = models.CharField(max_length=10)
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    cantidad_stock = models.IntegerField()
    proveedor = models.ForeignKey(Proveedor, on_delete=models.PROTECT)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

# ============================== Clientes ===========================
class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    direccion = models.TextField()
    telefono = models.CharField(max_length=20)
    correo_electronico = models.EmailField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

# ===================[Compras]========================
class Compra(models.Model):
    fecha_compra = models.DateTimeField(auto_now_add=True)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    def __str__(self):
        return f"Compra #{self.id} - {self.fecha_compra}"

class DetalleCompra(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Detalle de compra #{self.id}"

    
# ====================[Ventas]==============================
class Venta(models.Model):
    fecha_venta = models.DateTimeField(auto_now_add=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)                              

    def __str__(self):
        return f"Venta #{self.id} - {self.fecha_venta}"

class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Detalle de venta #{self.id}"
    

AdrileBoutique/appTiendaInventario/forms.py
from django import forms
from .models import Compra

class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = '__all__'

from django import forms 
from .models import  DetalleCompra

class DetalleCompraForm(forms.ModelForm):
    class Meta:
        model = DetalleCompra
        fields = '__all__'
        
# =======================================================================
from django import forms
from .models import Compra

class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = ['proveedor']

    def __init__(self, *args, **kwargs):
        super(CompraForm, self).__init__(*args, **kwargs)
        self.fields['proveedor'].widget.attrs['class'] = 'selectpicker'  # Añade clases CSS si es necesario
        self.fields['proveedor'].queryset = Proveedor.objects.all()  # Ajusta el queryset según tus necesidades
        
# forms.py
from django import forms
from .models import DetalleCompra

DetalleCompraFormSet = forms.inlineformset_factory(Compra, DetalleCompra, fields=['producto', 'cantidad', 'precio_unitario'])
        
# =============================================================================================================

from django import forms
from .models import Venta

class VentaForm(forms.Form):
    class Meta:
        model = Venta
        fields = '__all__'

from django import forms
from .models import DetalleVenta

class DetalleVentaForm(forms.ModelForm):
    class Meta:
        model = DetalleVenta
        fields = '__all__'
    
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['codigo', 'nombre', 'descripcion', 'precio', 'talla', 'categoria', 'cantidad_stock', 'proveedor', 'imagen', 'estado']

from django import forms
from .models import Categoria

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = '__all__'
        
from django import forms
from .models import Proveedor

class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = '__all__'
        
from django import forms
from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

AdrileBoutique/appTiendaInventario/templates/agregar_categoria.html
{% extends 'inventario/index.html' %}

{% block contenido %}

<body>
    <h1>{% if categoria %}Editar{% else %}Agregar{% endif %} Categoría</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% if categoria %}Guardar Cambios{% else %}Agregar{% endif %}">
        <a class="btn buttons mx-1" href="{% url 'lista_categorias' %}">
            volver
          </a>
    </form>
    {% endblock %}

AdrileBoutique/appTiendaInventario/templates/agregar_producto.html
<!DOCTYPE html>
<html>
<head>
    <title>{% if producto %}Editar Producto{% else %}Agregar Producto{% endif %}</title>
</head>
<body>
    <h1>{% if producto %}Editar Producto{% else %}Agregar Producto{% endif %}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% if producto %}Guardar Cambios{% else %}Agregar Producto{% endif %}">
    </form>
    {% if producto %}
        <form method="post" action="{% url 'cambiar_estado' producto.id %}">
            {% csrf_token %}
            <button type="submit">Cambiar Estado</button>
        </form>
    {% endif %}
</body>
</html>

AdrileBoutique/appTiendaInventario/templates/agregar_proveedor.html
<!DOCTYPE html>
<html>
<head>
    <title>{% if proveedor %}Editar{% else %}Agregar{% endif %} Proveedor</title>
</head>
<body>
    <h1>{% if proveedor %}Editar{% else %}Agregar{% endif %} Proveedor</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% if proveedor %}Guardar Cambios{% else %}Agregar{% endif %}">
    </form>
</body>
</html>

AdrileBoutique/appTiendaInventario/templates/editar_categoria.html
<!DOCTYPE html>
<html>
<head>
    <title>{% if categoria %}Editar{% else %}Agregar{% endif %} Categoría</title>
</head>
<body>
    <h1>{% if categoria %}Editar{% else %}Agregar{% endif %} Categoría</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% if categoria %}Guardar Cambios{% else %}Agregar{% endif %}">
    </form>
</body>
</html>

AdrileBoutique/appTiendaInventario/templates/editar_proveedor.html
<!DOCTYPE html>
<html>
<head>
    <title>{% if proveedor %}Editar{% else %}Agregar{% endif %} Proveedor</title>
</head>
<body>
    <h1>{% if proveedor %}Editar{% else %}Agregar{% endif %} Proveedor</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% if proveedor %}Guardar Cambios{% else %}Agregar{% endif %}">
    </form>
</body>
</html>

AdrileBoutique/appTiendaInventario/templates/index.html
{% extends 'tienda/index.html' %}
{% load static %}
{% block content_main %}

    <div class="content">
        {% block content %}
        <div class="row">
            <div class="col-md-6">
                <!-- Contenido principal de tu página -->
                <img src="{% static 'images/inventario.png' %}" alt="Inventario de Ropa" width="400" class="img-fluid">
                <h2>Adrile Boutique</h2>
                <p>Tu tienda de moda para todas las ocasiones.</p>
            </div>
            <div class="col-md-6">
                <!-- Formulario de inicio de sesión -->
                <div class="card shadow card-login p-3">
                    <div class="card-header bg-dark text-white">
                        <h4 class="text-center mt-2 canter"><i class="fa fa-solid fa-user fa-2xl iconoUser"></i></h4>
                    </div>
                    {% if error_message %}
                    <script>
                        toastr.options = {"closeButton": true,"debug": false,"newestOnTop": false,"progressBar": true,"positionClass": "toast-top-right",
                            "preventDuplicates": true,"onclick": null, "showDuration": "500","hideDuration": "1000", "timeOut": "5000",
                            "extendedTimeOut": "1000","showEasing": "swing", "hideEasing": "linear","showMethod": "fadeIn","hideMethod": "fadeOut"
                        };
                        
                        toastr.error('{{error_message}}');
                    </script>
                    {% endif %}
                    <div class="card-body">
                        <form method="post" action="{% url 'login' %}">
                            {% csrf_token %}
                            <div class="form-floating">
                                <input type="text" class="form-control" id="username" name="username" maxlength="150"
                                    placeholder="Usuario" required />
                                <label for="id_username"><i class="fa-solid fa-user fa-beat-fade"></i> Usuario</label>
                            </div>
                            <div class="form-floating mt-3">
                                <input type="password" class="form-control" id="password" name="password"
                                    placeholder="contraseña" required />
                                </i><label for="id_password"><i class="fa-solid fa-key fa-beat-fade"></i>
                                    Contraseña</label>
                            </div>
                            <div class="form-check mt-3">
                                <input class="form-check-input" type="checkbox" id="remember_me" name="remember_me">
                                <label class="form-check-label" for="remember_me">Recuérdame</label>
                            </div>
                            <div class="form-floating col mt-3 text-center"><button type="submit"
                                    class="btn btn-primary btn-block canter2">
                                    <i class="fa fa-sign-in"></i>
                                    &nbsp; Iniciar Sesión</button>
                            </div>
                        </form>
                        <div class="row">
                            <div class="col mt-3 text-center">
                                <a href="{% url 'validarCorreo' %}" class="link-secondary"> Olvido su contraseña ? </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer-l                                                                                                                                                                                                                                                                                                                                                                                                                                                            ogin">
                    <div class="col">
                        <small><a
                                href="https://www.freepik.es/vector-gratis/fondo-monocromatico-blanco-estilo-papel_15518074.htm#query=fondo&position=1&from_view=keyword&track=sph"
                                class="link-dark">Imagen
                                de pikisuperstar</a><span class="text-black"> en Freepik </span>
                        </small>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
    </div>

{% endblock %}

AdrileBoutique/appTiendaInventario/templates/informe_ventas.html
<!DOCTYPE html>
<html>
<head>
    <title>Informe de Ventas</title>
</head>
<body>
    <h1>Informe de Ventas</h1>
    <h2>Total de Ventas: {{ total_ventas.total }}</h2>
    <table>
        <tr>
            <th>Fecha</th>
            <th>Cliente</th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Precio Unitario</th>
        </tr>
        {% for venta in ventas %}
            {% for detalle in venta.detalleventa_set.all %}
                <tr>
                    <td>{{ venta.fecha_venta }}</td>
                    <td>{{ venta.cliente }}</td>
                    <td>{{ detalle.producto }}</td>
                    <td>{{ detalle.cantidad }}</td>
                    <td>{{ detalle.precio_unitario }}</td>
                </tr>
            {% endfor %}
        {% endfor %}
    </table>
</body>
</html>

AdrileBoutique/appTiendaInventario/templates/lista_categorias.html
{% extends 'inventario/index.html' %}

{% block contenido %}
<h1>Lista de Categorías</h1>
<hr>
<div class="row">
    <div class="col d-flex justify-content-center">
        <a href="{% url 'agregar_categoria' %}" class="btn btn-primary">Agregar Categoria</a>
        
    </div>
  </div>
<hr>
<div class="row mx-2 d-flex justify-content-center">
    <div class="col-10">
        <table id="category-table" class="display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Categoría</th>
                    <th>Imagen</th>
                    <th>Cat. padre(Opcional)</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for categoria in categorias %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ categoria.nombre }}</td>
                    <td><img src="/media/{{ categoria.imagen }}" alt="{{ categoria.nombre }}" width="50"></td>
                    <td>{{ categoria.categoria_padre }}</td>
                    <td><button class="btn buttons" data-bs-toggle="modal" data-bs-target="#detalleVentaModal"
                            onclick="detalle('{{ venta.id }}')">Ver Detalles</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var table = document.getElementById("category-table");
        var dataTable = new DataTable(table, {
            "language": {
                url: "//cdn.datatables.net/plug-ins/1.13.6/i18n/es-CO.json"
            },
            "paging": false,
            "scrollCollapse": true,
            "scrollY": "40vh",
            "scrollX": "100%",
            responsive: true
        });

        dataTable.columns.adjust();
    });
</script>

{% endblock %}

AdrileBoutique/appTiendaInventario/templates/lista_clientes.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Clientes</title>
</head>
<body>
    <h1>Lista de Clientes</h1>
    <ul>
        {% for cliente in clientes %}
            <li>{{ cliente.nombre }} {{ cliente.apellido }}</li>
        {% endfor %}
    </ul>
</body>
</html>

AdrileBoutique/appTiendaInventario/templates/lista_compras.html
{% extends 'inventario/index.html'%}
{% block contenido %}
{% load static %}

<div class="loader-wrapper">
    <div class="loader"></div>
</div>

<h1>Lista de Entradas</h1>
<hr>

<div class=" ">
    <div class="col d-flex justify-content-center">
        <a href="{% url 'entradas' %}" class="btn btn-primary">Agregar Entrada</a>
    </div>
</div>

<hr>
<div class=" mx-2 d-flex justify-content-center">
    <div class="col-10">
        <table id="compras-table" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Fecha de Compra</th>
                    <th>Proveedor</th>
                    <th># de Productos</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for compra in compras %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ compra.fecha_compra }}</td>
                    <td>{{ compra.proveedor }}</td>
                    <td>{{ compra.total_cantidad }}</td>
                    <td>
                        <a class="btn " data-bs-toggle="modal" data-bs-target="#detalleCompraModal"
                            onclick="detalle('{{ compra.id }}')" title="Ver detalles">
                            <i class="fa-solid fa-eye"></i>
                        </a>
                        <a onclick="invalidarCompra('{{ compra.id }}')" title="Eliminar" class="btn">
                            <i class="fa-solid fa-circle-xmark"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="detalleCompraModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Detalles de la Compra</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="contenidoDetalle">
                    <!-- contenido venta -->
                </div>

                <h4>Detalles de la Compra:</h4>
                <table class="table table-dark ">
                    <thead>
                        <tr>
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th>Precio Unitario</th>
                        </tr>
                    </thead>
                    <tbody id="datos">
                        <!-- datos  -->
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/lista_compras.js' %}"></script>

{% endblock %}

AdrileBoutique/appTiendaInventario/templates/lista_productos.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Productos</title>
</head>
<body>
    <h1>Lista de Productos</h1>
    <ul>
        {% for producto in productos %}
            <li>{{ producto.nombre }} - {{producto.estado}}</li> 
        {% endfor %}
    </ul>
</body>
</html>

AdrileBoutique/appTiendaInventario/templates/lista_proveedores.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Proveedores</title>
</head>
<body>
    <h1>Lista de Proveedores</h1>
    <ul>
        {% for proveedor in proveedores %}
            <li>{{ proveedor.nombre_empresa }}</li>
        {% endfor %}
    </ul>
</body>
</html>

AdrileBoutique/appTiendaInventario/templates/lista_stock.html
{% extends 'inventario/index.html'%}
{% block contenido %}

<div class="row mb-2 mx-1">
    <h1 class="text-center">Stock de Productos</h1>
</div>

<div class="row mx-1">
    <div class="col d-flex justify-content-md-evenly mb-2">
        <button type="button" class="btn btn-primary mx-1" onclick="history.back()">
            <i class="fa-solid fa-arrow-left"></i>
            volver
        </button>
        <button type="button" class="btn btn-primary mx-1" onclick="location.href='/dashboard/'">
            <i class="fa-solid fa-ban"></i>
            Cancelar
        </button>
    </div>
</div>

<div class="row justify-content-center mx-1">
    <div class="col-10">
        <table id="productosTable" class="display" style="width: 100%;">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Codigo</th>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Nueva</th>
                    <th>opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ producto.codigo }}</td>
                    <td>{{ producto.nombre }}</td>
                    <td>
                        <span id="original-cantidad-{{ producto.id }}">{{ producto.cantidad_stock }}</span>
                    </td>
                    <td>
                        <input type="number" class="rounded" id="edit-cantidad-{{ producto.id }}" min="0">
                    </td>
                    <td>
                        <button class="btn buttons" onclick="change_stock('{{ producto.id }}')">Editar</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>

<script>
    var dataTable;
    document.addEventListener("DOMContentLoaded", function () {
        dataTable = $('#productosTable').DataTable({
            "language": {
                url: "//cdn.datatables.net/plug-ins/1.13.6/i18n/es-CO.json"
            },
            "paging": false,
            "scrollCollapse": true,
            "scrollY": "40vh",
            responsive: true
        });
    });

    function change_stock(id) {
        var cantidadInput = document.getElementById("edit-cantidad-" + id);
        var originalCantidad = document.getElementById("original-cantidad-" + id);

        if (cantidadInput.value >= 0) {
            axios.defaults.xsrfCookieName = 'csrftoken';
            axios.defaults.xsrfHeaderName = 'X-CSRFToken';
            axios.patch(`/api/productos/${id}/`, { "cantidad_stock": cantidadInput.value })
                .then(function (response) {
                    // Actualiza la cantidad original para reflejar los cambios
                    originalCantidad.textContent = cantidadInput.value;
                    console.log(response);
                    cantidadInput.value = ""
                })
                .catch(function (error) {
                    // Maneja errores si es necesario
                    console.error(error);
                });
        } else {
            Swal.fire({
                icon: 'error',
                title: 'Error',
                text: 'Ingresa un número positivo o cero.',
                confirmButtonColor: '#0d6efd',
            })
            cantidadInput.value = originalCantidad.textContent;
        }
    }

</script>

{% endblock %}